/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import mockia.calculations.Calculations;
import mockia.data.*;
import mockia.exchangeRates.ExchangeRates;
import mockia.expenditures.*;

/**
 *
 * @author ethanli
 */
public class guiFrame extends javax.swing.JFrame {

    /**
     * Creates new form guiFrame by initializing all components, creating date
     * format the user sees, and updating the all the text fields with data
     * from the database (Previous data inputted)
     */
    public guiFrame()
    {
        try
        {
            initComponents();
            LocalDate localDate = LocalDate.now();
            String date = localDate.toString();
            this.date.setText(date);
            updateTextFields(Database.createObjects());
        }
        catch (Exception e)
        {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        todaysSpending = new javax.swing.JLabel();
        monthsSpending = new javax.swing.JLabel();
        tBills = new javax.swing.JLabel();
        tTransport = new javax.swing.JLabel();
        tLunch = new javax.swing.JLabel();
        tGroceries = new javax.swing.JLabel();
        tOccasional = new javax.swing.JLabel();
        tTotal = new javax.swing.JLabel();
        mGroceries = new javax.swing.JLabel();
        mOccasional = new javax.swing.JLabel();
        mTotal = new javax.swing.JLabel();
        mBills = new javax.swing.JLabel();
        mTransport = new javax.swing.JLabel();
        mLunch = new javax.swing.JLabel();
        inputSpending = new javax.swing.JLabel();
        inputSpendingTextField = new javax.swing.JTextField();
        spendingType = new javax.swing.JLabel();
        spendingBox = new javax.swing.JComboBox<>();
        spendingDate = new javax.swing.JLabel();
        spendingDayBox = new javax.swing.JComboBox<>();
        todaysDate = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        spendingMonthBox = new javax.swing.JComboBox<>();
        spendingYearBox = new javax.swing.JComboBox<>();
        year = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mBillsT = new javax.swing.JTextField();
        mTransportT = new javax.swing.JTextField();
        mLunchT = new javax.swing.JTextField();
        mGroceriesT = new javax.swing.JTextField();
        mOccasionalT = new javax.swing.JTextField();
        mTotalT = new javax.swing.JTextField();
        tSpendingPanel = new javax.swing.JPanel();
        tBillsT = new javax.swing.JTextField();
        tTransportT = new javax.swing.JTextField();
        tLunchT = new javax.swing.JTextField();
        tGroceriesT = new javax.swing.JTextField();
        tOccasionalT = new javax.swing.JTextField();
        tTotalT = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        yearsSpending = new javax.swing.JLabel();
        tSpendingPanel1 = new javax.swing.JPanel();
        yBillsT = new javax.swing.JTextField();
        yTransportT = new javax.swing.JTextField();
        yLunchT = new javax.swing.JTextField();
        yGroceriesT = new javax.swing.JTextField();
        yOccasionalT = new javax.swing.JTextField();
        yTotalT = new javax.swing.JTextField();
        yGroceries = new javax.swing.JLabel();
        yBills = new javax.swing.JLabel();
        yOccasional = new javax.swing.JLabel();
        yTransport = new javax.swing.JLabel();
        yLunch1 = new javax.swing.JLabel();
        yTotal = new javax.swing.JLabel();
        HKDText = new javax.swing.JLabel();
        selectCurrency = new javax.swing.JComboBox<>();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        todaysSpending.setText("Today's Spending");

        monthsSpending.setText("Month's Spending");

        tBills.setText("Bills          ");

        tTransport.setText("Transport ");

        tLunch.setText("Lunch (Meals)");

        tGroceries.setText("Groceries ");

        tOccasional.setText("Occasional");

        tTotal.setText("Total");

        mGroceries.setText("Groceries");

        mOccasional.setText("Occasional");

        mTotal.setText("Total");

        mBills.setText("Bills");

        mTransport.setText("Transport");

        mLunch.setText("Lunch (Meals)");

        inputSpending.setText("Input Spending");

        spendingType.setText("Spending Type");

        spendingBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bills", "Transport", "Lunch", "Groceries", "Occasional" }));

        spendingDate.setText("Spending Date");

        spendingDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        todaysDate.setText("Today's Date:");

        day.setText("Day");

        month.setText("Month");

        spendingMonthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        spendingYearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        year.setText("Year");

        submit.setText("Sumbit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        mBillsT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        mTransportT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        mLunchT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        mGroceriesT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        mOccasionalT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        mTotalT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mBillsT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mTransportT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mLunchT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mGroceriesT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mOccasionalT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mTotalT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mBillsT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTransportT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mLunchT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mGroceriesT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mOccasionalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTotalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tBillsT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        tTransportT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        tLunchT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        tGroceriesT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        tOccasionalT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        tTotalT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        javax.swing.GroupLayout tSpendingPanelLayout = new javax.swing.GroupLayout(tSpendingPanel);
        tSpendingPanel.setLayout(tSpendingPanelLayout);
        tSpendingPanelLayout.setHorizontalGroup(
            tSpendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tSpendingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tSpendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tBillsT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTransportT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLunchT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tGroceriesT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tOccasionalT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTotalT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        tSpendingPanelLayout.setVerticalGroup(
            tSpendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tSpendingPanelLayout.createSequentialGroup()
                .addComponent(tBillsT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tTransportT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tLunchT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tGroceriesT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tOccasionalT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tTotalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tBillsT.getAccessibleContext().setAccessibleParent(mTransportT);

        yearsSpending.setText("Year's Spending");
        yearsSpending.setToolTipText("");

        yBillsT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        yTransportT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        yLunchT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        yGroceriesT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        yOccasionalT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        yTotalT.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        yGroceries.setText("Groceries ");

        yBills.setText("Bills          ");

        yOccasional.setText("Occasional");

        yTransport.setText("Transport ");

        yLunch1.setText("Lunch (Meals)");

        yTotal.setText("Total");

        javax.swing.GroupLayout tSpendingPanel1Layout = new javax.swing.GroupLayout(tSpendingPanel1);
        tSpendingPanel1.setLayout(tSpendingPanel1Layout);
        tSpendingPanel1Layout.setHorizontalGroup(
            tSpendingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tSpendingPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tSpendingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yTotal)
                    .addComponent(yGroceries)
                    .addComponent(yTransport)
                    .addComponent(yLunch1)
                    .addComponent(yBills)
                    .addComponent(yOccasional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tSpendingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yBillsT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yTransportT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yLunchT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yGroceriesT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yOccasionalT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yTotalT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        tSpendingPanel1Layout.setVerticalGroup(
            tSpendingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tSpendingPanel1Layout.createSequentialGroup()
                .addGroup(tSpendingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tSpendingPanel1Layout.createSequentialGroup()
                        .addComponent(yBills)
                        .addGap(18, 18, 18)
                        .addComponent(yTransport)
                        .addGap(18, 18, 18)
                        .addComponent(yLunch1)
                        .addGap(18, 18, 18)
                        .addComponent(yGroceries)
                        .addGap(18, 18, 18)
                        .addComponent(yOccasional)
                        .addGap(18, 18, 18)
                        .addComponent(yTotal))
                    .addGroup(tSpendingPanel1Layout.createSequentialGroup()
                        .addComponent(yBillsT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yTransportT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yLunchT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yGroceriesT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yOccasionalT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yTotalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HKDText.setText("HKD($)");

        selectCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HKD($)", "USD($)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HKDText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(todaysSpending)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tTotal)
                                    .addComponent(tGroceries)
                                    .addComponent(tTransport)
                                    .addComponent(tLunch)
                                    .addComponent(tBills)
                                    .addComponent(tOccasional))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tSpendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mBills)
                                    .addComponent(mTotal)
                                    .addComponent(mOccasional)
                                    .addComponent(mGroceries)
                                    .addComponent(mLunch)
                                    .addComponent(mTransport))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(monthsSpending))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearsSpending)
                            .addComponent(tSpendingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spendingDate)
                                        .addGap(18, 18, 18)
                                        .addComponent(spendingDayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spendingMonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(todaysDate)
                                        .addGap(24, 24, 24)
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spendingYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(year))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputSpending)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputSpendingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(selectCurrency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spendingType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spendingBox, 0, 133, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(day)
                                        .addGap(44, 44, 44)
                                        .addComponent(month)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HKDText)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(todaysSpending)
                        .addComponent(monthsSpending))
                    .addComponent(yearsSpending, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tBills)
                                .addGap(18, 18, 18)
                                .addComponent(tTransport)
                                .addGap(18, 18, 18)
                                .addComponent(tLunch)
                                .addGap(18, 18, 18)
                                .addComponent(tGroceries)
                                .addGap(18, 18, 18)
                                .addComponent(tOccasional)
                                .addGap(18, 18, 18)
                                .addComponent(tTotal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mBills)
                                .addGap(18, 18, 18)
                                .addComponent(mTransport)
                                .addGap(18, 18, 18)
                                .addComponent(mLunch)
                                .addGap(18, 18, 18)
                                .addComponent(mGroceries)
                                .addGap(18, 18, 18)
                                .addComponent(mOccasional)
                                .addGap(18, 18, 18)
                                .addComponent(mTotal))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tSpendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tSpendingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSpending)
                    .addComponent(inputSpendingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spendingType)
                    .addComponent(spendingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day)
                    .addComponent(month)
                    .addComponent(year))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spendingDate)
                    .addComponent(spendingDayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spendingMonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spendingYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todaysDate)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Updates all the text fields shown on the GUI
     * @param expenditures ArrayList of expenditures
     */
    private void updateTextFields(ArrayList<Expenditures> expenditures)
    {
        try
        {
            //Date Format From (From Mkyong)
            LocalDate localDate = LocalDate.now();
            String date = localDate.toString();
            System.out.println(date);
            String year = date.substring(0, 4);
            String month = date.substring(5, 7);
            String day = date.substring(8, 10);

            //Update 1st Column
            double dayBills = Calculations.calculateDay(expenditures, 
                    day, month, year, "Bills");
            String dBills = String.format("%.2f", dayBills);
            tBillsT.setText(dBills);

            double dayTransport = Calculations.calculateDay(expenditures, 
                    day, month, year, "Transport");
            String dTransport = String.format("%.2f", dayTransport);
            tTransportT.setText(dTransport);

            double dayLunch = Calculations.calculateDay(expenditures, 
                    day, month, year, "Lunch");
            String dLunch = String.format("%.2f", dayLunch);
            tLunchT.setText(dLunch);

            double dayGroceries = Calculations.calculateDay(expenditures, 
                    day, month, year, "Groceries");
            String dGroceries = String.format("%.2f", dayGroceries);
            tGroceriesT.setText(dGroceries);

            double dayOccasional = Calculations.calculateDay(expenditures, 
                    day, month, year, "Occasional");
            String dOccasional = String.format("%.2f", dayOccasional);
            tOccasionalT.setText(dOccasional);

            double dayAll = Calculations.calculateDay(expenditures, 
                    day, month, year, "all");
            String dAll = String.format("%.2f", dayAll);
            tTotalT.setText(dAll);
            
            //Update 2nd Column
            double monthBills = Calculations.calculateMonth(expenditures, 
                    month, year, "Bills");
            String mBills = String.format("%.2f", monthBills);
            mBillsT.setText(mBills);
            
            double monthTransport = Calculations.calculateMonth(expenditures, 
                    month, year, "Transport");
            String mTransport = String.format("%.2f", monthTransport);
            mTransportT.setText(mTransport); 
            
            double monthLunch = Calculations.calculateMonth(expenditures, 
                    month, year, "Lunch");
            String mLunch = String.format("%.2f", monthLunch);
            mLunchT.setText(mLunch); 
            
            double monthGroceries = Calculations.calculateMonth(expenditures, 
                    month, year, "Groceries");
            String mGroceries = String.format("%.2f", monthGroceries);
            mGroceriesT.setText(mGroceries); 
            
            double monthOccasional = Calculations.calculateMonth(expenditures, 
                    month, year, "Occasional");
            String mOccasional = String.format("%.2f", monthOccasional);
            mOccasionalT.setText(mOccasional); 
            
            double monthAll = Calculations.calculateMonth(expenditures, 
                    month, year, "all");
            String mAll = String.format("%.2f", monthAll);
            mTotalT.setText(mAll); 
            
            //Update 3rd Column
            double yearBills = Calculations.calculateYear(expenditures, 
                    year, "Bills");
            String yBills = String.format("%.2f", yearBills);
            yBillsT.setText(yBills);
            
            double yearTransport = Calculations.calculateYear(expenditures, 
                    year, "Transport");
            String yTransport = String.format("%.2f", yearTransport);
            yTransportT.setText(yTransport);
            
            double yearLunch = Calculations.calculateYear(expenditures, 
                    year, "Lunch");
            String yLunch = String.format("%.2f", yearLunch);
            yLunchT.setText(yLunch);
            
            double yearGroceries = Calculations.calculateYear(expenditures, 
                    year, "Groceries");
            String yGroceries = String.format("%.2f", yearGroceries);
            yGroceriesT.setText(yGroceries);
            
            double yearOccasional = Calculations.calculateYear(expenditures, 
                    year, "Occasional");
            String yOccasional = String.format("%.2f", yearOccasional);
            yOccasionalT.setText(yOccasional);
            
            double yearTotal = Calculations.calculateYear(expenditures, 
                    year, "all");
            String yTotal = String.format("%.2f", yearTotal);
            yTotalT.setText(yTotal);   
        }
        catch (Exception e)
        {
        }
    }
    
    /**
     * Updates all the java objects when the submit button is pressed by using 
     * all the info on the GUI
     * The data is then updated by calling updateTextFields
     * @param evt When the submit button is pressed
     */
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try
        {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/mm/dd");
            LocalDate localDate = LocalDate.now();
            String date = localDate.toString();
            String tYear = date.substring(0, 4);
            String tMonth = date.substring(5, 7);
            String tDay = date.substring(8, 10);
            
            String day = "";
            String month = "";
            String year = "";
            
            //User's input under spending type
            double spending = 
                    Double.parseDouble(inputSpendingTextField.getText());

            if (selectCurrency.getSelectedItem().toString().equals("USD($)"))
            {
               spending = ExchangeRates.convert(spending);
            }
            
            String type = spendingBox.getSelectedItem().toString();
            
            if (spendingDayBox.getSelectedItem().toString().equals("Today"))
            {
               day = tDay;
            }
            else
            {
                day = spendingDayBox.getSelectedItem().toString();
            }
          
            if (spendingMonthBox.getSelectedItem().toString().equals("Today"))
            {
                month = tMonth;
            }
            else
            {
                switch (spendingMonthBox.getSelectedItem().toString())
                {
                    case "Jan":
                        month = "01";
                        break;
                    case "Feb":
                        month = "02";
                        break;
                    case "Mar":
                        month = "03";
                        break;
                    case "Apr":
                        month = "04";
                        break;
                    case "May":
                        month = "05";
                        break;
                    case "Jun":
                        month = "06";
                        break;
                    case "Jul":
                        month = "07";
                        break;
                    case "Aug":
                        month = "08";
                        break;
                    case "Sep":
                        month = "09";
                        break;
                    case "Oct":
                        month = "10";
                        break;
                    case "Nov":
                        month = "11";
                        break;
                    case "Dec":
                        month = "12";
                        break;
                }
            }

            if (spendingYearBox.getSelectedItem().toString().equals("Today"))
            {
                year = tYear;
            }
            else
            {
                year = spendingYearBox.getSelectedItem().toString();
            }
            
            //Posts the users input to database (Sent to database class, method
            //post)
            Database.post(day, month, year, spending, type);
            ArrayList<Expenditures> expenditures = Database.createObjects();
            updateTextFields(expenditures);
            System.out.println(spending);
        }
        catch (Exception e)
        {
            //Error message when user inputs invalid inputs into the "Spending
            //Input" text box
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Number", 
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * GUI Main
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new guiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HKDText;
    private javax.swing.JTextField date;
    private javax.swing.JLabel day;
    private javax.swing.JLabel inputSpending;
    private javax.swing.JTextField inputSpendingTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel mBills;
    private javax.swing.JTextField mBillsT;
    private javax.swing.JLabel mGroceries;
    private javax.swing.JTextField mGroceriesT;
    private javax.swing.JLabel mLunch;
    private javax.swing.JTextField mLunchT;
    private javax.swing.JLabel mOccasional;
    private javax.swing.JTextField mOccasionalT;
    private javax.swing.JLabel mTotal;
    private javax.swing.JTextField mTotalT;
    private javax.swing.JLabel mTransport;
    private javax.swing.JTextField mTransportT;
    private javax.swing.JLabel month;
    private javax.swing.JLabel monthsSpending;
    private javax.swing.JComboBox<String> selectCurrency;
    private javax.swing.JComboBox<String> spendingBox;
    private javax.swing.JLabel spendingDate;
    private javax.swing.JComboBox<String> spendingDayBox;
    private javax.swing.JComboBox<String> spendingMonthBox;
    private javax.swing.JLabel spendingType;
    private javax.swing.JComboBox<String> spendingYearBox;
    private javax.swing.JButton submit;
    private javax.swing.JLabel tBills;
    private javax.swing.JTextField tBillsT;
    private javax.swing.JLabel tGroceries;
    private javax.swing.JTextField tGroceriesT;
    private javax.swing.JLabel tLunch;
    private javax.swing.JTextField tLunchT;
    private javax.swing.JLabel tOccasional;
    private javax.swing.JTextField tOccasionalT;
    private javax.swing.JPanel tSpendingPanel;
    private javax.swing.JPanel tSpendingPanel1;
    private javax.swing.JLabel tTotal;
    private javax.swing.JTextField tTotalT;
    private javax.swing.JLabel tTransport;
    private javax.swing.JTextField tTransportT;
    private javax.swing.JLabel todaysDate;
    private javax.swing.JLabel todaysSpending;
    private javax.swing.JLabel yBills;
    private javax.swing.JTextField yBillsT;
    private javax.swing.JLabel yGroceries;
    private javax.swing.JTextField yGroceriesT;
    private javax.swing.JLabel yLunch1;
    private javax.swing.JTextField yLunchT;
    private javax.swing.JLabel yOccasional;
    private javax.swing.JTextField yOccasionalT;
    private javax.swing.JLabel yTotal;
    private javax.swing.JTextField yTotalT;
    private javax.swing.JLabel yTransport;
    private javax.swing.JTextField yTransportT;
    private javax.swing.JLabel year;
    private javax.swing.JLabel yearsSpending;
    // End of variables declaration//GEN-END:variables
}